name: CI - macOS/Linux (pixi)

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - '*.md'
      - LICENSE
      - .pre-commit-config.yaml
      - CHANGELOG.md
  pull_request:
    paths-ignore:
      - .gitignore
      - '*.md'
      - LICENSE
      - .pre-commit-config.yaml
      - CHANGELOG.md
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  candlewick-pixi:
    name: ${{ matrix.os }} - env ${{ matrix.environment }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
    env:
      CCACHE_BASEDIR: "${GITHUB_WORKSPACE}"
      CCACHE_DIR: "${GITHUB_WORKSPACE}/.ccache"
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 5
      # Since pixi will install a compiler, the compiler mtime will be changed.
      # This can invalidate the cache (https://ccache.dev/manual/latest.html#config_compiler_check)
      CCACHE_COMPILERCHECK: content
      BUILD_ADVANCED_TESTING: ${{ matrix.BUILD_ADVANCED_TESTING }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        environment: [all-test]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/cache@v4
      with:
        path: .ccache
        key: ccache-macos-linux-pixi-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.environment }}-${{ github.sha }}
        restore-keys: ccache-macos-linux-pixi-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.environment }}-

    - uses: prefix-dev/setup-pixi@v0.8.4
      with:
        cache: true
        environments: ${{ matrix.environment }}

    - name: Build candlewick [macOS/Linux]
      env:
        CMAKE_BUILD_PARALLEL_LEVEL: 2
        CANDLEWICK_BUILD_TYPE: ${{ matrix.build_type }}
      run: |
        # Clear ccache statistics
        pixi run -e ${{ matrix.environment }} ccache -z

        pixi run -e ${{ matrix.environment }} build

    - name: Test candlewick [macOS/Linux]
      run: |
        pixi run -e ${{ matrix.environment }} ctest --test-dir build --output-on-failure

    - name: Display ccache statistics
      shell: bash -el {0}
      run: |
        pixi run -e ${{ matrix.environment }} ccache -sv

  check:
    if: always()
    name: check-macos-linux-pixi

    needs:
    - candlewick-pixi

    runs-on: Ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
